grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.127.0.0.1.nip.io
    path: /
    pathType: ImplementationSpecific
    tls:
      - hosts:
          - grafana.127.0.0.1.nip.io
        secretName: grafana-tls

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.127.0.0.1.nip.io
    path: /
    pathType: ImplementationSpecific
    tls:
      - hosts:
          - prometheus.127.0.0.1.nip.io
        secretName: prometheus-tls
