image:
  repository: santy1504/finsight-api
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: finsight.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
