image:
  repository: temple-booking-api
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false

resources: {}

serviceAccount:
  create: true
  name: ""

replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
