name: Deploy Monitoring Stack

on:
  push:
    paths:
      - "deployments/helm-charts/monitoring/**"
      - ".github/workflows/deploy-monitoring.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Kubeconfig
      run: |
        mkdir ~/.kube
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

    - name: Setup Helm
      uses: azure/setup-helm@v3

    - name: Deploy Prometheus and Grafana
      run: |
        helm upgrade --install monitoring deployments/helm-charts/monitoring \
          --namespace monitoring --create-namespace \
          -f deployments/helm-charts/monitoring/values.yaml
