name: Deploy Monitoring Stack

on:
  push:
    branches: [ dev ]
    paths:
      - 'deployments/helm-charts/**'
      - '.github/workflows/deploy-monitoring.yaml'

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig
        mkdir -p ~/.kube
        mv kubeconfig ~/.kube/config

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Add Prometheus Helm Repo
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update

    - name: Deploy Prometheus Stack
      run: |
        helm upgrade --install prometheus \
          prometheus-community/kube-prometheus-stack \
          -f deployments/helm-charts/prometheus-values.yaml \
          -n monitoring --create-namespace

    - name: Confirm Install
      run: |
        kubectl get pods -n monitoring
